### ISSUE TITLE
无法克隆gitlab-workhorse

### ISSUE THREAD

**Issue by s2005lg** [clarkhan/docker-gitlab#3]
`exec_as_git git clone -q -b ${GITLAB_WORKHORSE_VERSION} --depth 1 ${GITLAB_WORKHORSE_CLONE_URL} ${GITLAB_WORKHORSE_INSTALL_DIR}`

自己build时，提示这个 -b ${GITLAB_WORKHORSE_VERSION} 这个branch 不存在

**Comment by clarkhan** [comment]
8.5.4 应该有的。官方的 DockerHub 和 阿里云中也都上传了。都是通过这个仓库自动构建的。可以参考 [Readme 的 安装](https://github.com/clarkhan/docker-gitlab#安装) 。如果是更新的版本，现在还没有跟进。
